version: '3'
services:
  testrpc:
    build: ../testrpc
    image: ethereumjs/testrpc:latest
    ports:
     - '8546:8546'
    command: testrpc -p 8546 -i testrpc -h 0.0.0.0
  truffle3:
    image: dougvk/truffle3:latest
    command: bash
    stdin_open: true
    tty: true
    ports:
      - "7001:8080"
    volumes:
      - ../:/app
